### ISSUE TITLE
Mixed boundary condition

### ISSUE THREAD

**Issue by carusonahuel** [csrc-sdsu/mole#5]
Hi,

My name is Nahuel Caruso, I've just taken a Mimetic Method course by Prof. Castillo and I have a question:

Is there any mixed boundary condition tool?

I would like to solve a Helmholtz equation in 1D with mixed boundary conditions.

I could explain the problem that I have to solve if there was needed.

Best regards
Nahuel

**Comment by aboada** [comment]
Nahuel,

The tool you are referring to needs to be implemented.

In the meantime, since you are working in 1D, you must modify the first
(west boundary) and last row (east boundary) of the corresponding mimetic
operator to specify the mixed boundary conditions. Make sure to change the
RHS accordingly.

Let me know if you have any questions.

Thanks,
Angel Boada

**Comment by jcorbino** [comment]
Hi @carusonahuel - It is not a complex routine, but we have a long TO-DO list. I expect to have it working this year.

**Comment by jcorbino** [comment]
@carusonahuel  Apologies for the delay. I've added mixed BC operators for 1D, 2D, and 3D in C++ and MATLAB/Octave. If you use them, I'd appreciate any feedback on their correctness and performance.
